package com.valhallagame.featserviceclient.message;

public enum FeatName {
	EINHARJER_SLAYER, TRAINING_EFFICIENCY,

	/*---------- Fredstorp Feats -------------*/
	FREDSTORP_THIEF_OF_THIEVES,
	FREDSTORP_GAMBLER,
	FREDSTORP_ANORECTIC,
	FREDSTORP_NEVER_BEEN_BETTER,
	FREDSTORP_SPEEDRUNNER,
	FREDSTORP_EXTRACTOR,
	FREDSTORP_EXTERMINATOR
}
